services:
    combyna_bundle.cache_warmer.combyna:
        class: Combyna\CombynaBundle\CacheWarmer\CombynaCacheWarmer
        arguments:
            - '@combyna_bundle.server_bootstrap'
        tags:
            - {name: kernel.cache_warmer}
